USE websitebanhang;

ALTER TABLE Users
  ADD COLUMN RewardPoints INT NOT NULL DEFAULT 0 AFTER LockedUntil;

ALTER TABLE Orders
  MODIFY COLUMN PaymentMethod ENUM('COD','VNPAY','POINTS') NOT NULL,
  ADD COLUMN PointsUsed INT NOT NULL DEFAULT 0 AFTER TotalAmount;

CREATE TABLE IF NOT EXISTS RewardTransactions (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  OrderId INT NULL,
  Points INT NOT NULL,
  Type ENUM('ORDER_EARNED','REWARD_REDEEMED','ORDER_REVERSED','ADMIN_ADJUSTED') NOT NULL,
  Description VARCHAR(255) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE SET NULL ON UPDATE CASCADE,
  UNIQUE KEY unique_reward_order_type (OrderId, Type),
  INDEX idx_reward_transactions_user_created (UserId, CreatedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
