-- MySQL schema for OWEN website shop

CREATE DATABASE IF NOT EXISTS websitebanhang CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE websitebanhang;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS VnPayTransactions;
DROP TABLE IF EXISTS RefreshTokens;
DROP TABLE IF EXISTS Otps;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS CartProducts;
DROP TABLE IF EXISTS Carts;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS ProductVariants;
DROP TABLE IF EXISTS ProductImages;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Sizes;
DROP TABLE IF EXISTS Colors;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Brands;
DROP TABLE IF EXISTS Users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS Users (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  Role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
  Status ENUM('ACTIVE','LOCKED') NOT NULL DEFAULT 'ACTIVE',
  FailedLoginAttempts INT NOT NULL DEFAULT 0,
  LockedUntil DATETIME NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Brands (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Categories (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Colors (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Code VARCHAR(20) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_color(Code, Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Sizes (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Value VARCHAR(50) NOT NULL UNIQUE,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Products (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  SKU VARCHAR(60) NOT NULL UNIQUE,
  Title VARCHAR(200) NOT NULL,
  Description TEXT NULL,
  Price DECIMAL(10,2) NOT NULL,
  BrandId INT NOT NULL,
  CategoryId INT NULL,
  IsActive TINYINT(1) NOT NULL DEFAULT 1,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (BrandId) REFERENCES Brands(Id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ProductImages (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  ProductId INT NOT NULL,
  ImageUrl VARCHAR(500) NOT NULL,
  Position INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ProductVariants (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  ProductId INT NOT NULL,
  ColorId INT NOT NULL,
  SizeId INT NOT NULL,
  StockQty INT NOT NULL DEFAULT 0,
  Price DECIMAL(10,2) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_variant(ProductId, ColorId, SizeId),
  FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ColorId) REFERENCES Colors(Id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (SizeId) REFERENCES Sizes(Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Comments (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  ProductId INT NOT NULL,
  Rating TINYINT NOT NULL,
  Content TEXT NOT NULL,
  Status ENUM('VISIBLE','HIDDEN') NOT NULL DEFAULT 'VISIBLE',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  CHECK (Rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Carts (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  Status ENUM('ACTIVE','ABANDONED') NOT NULL DEFAULT 'ACTIVE',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY unique_active_cart(UserId, Status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CartProducts (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  CartId INT NOT NULL,
  ProductVariantId INT NOT NULL,
  Quantity INT NOT NULL DEFAULT 1,
  UnitPrice DECIMAL(10,2) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_cart_item(CartId, ProductVariantId),
  FOREIGN KEY (CartId) REFERENCES Carts(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ProductVariantId) REFERENCES ProductVariants(Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Orders (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderCode VARCHAR(50) NOT NULL UNIQUE,
  UserId INT NULL,
  RecipientName VARCHAR(150) NOT NULL,
  RecipientPhone VARCHAR(30) NOT NULL,
  RecipientAddress VARCHAR(500) NOT NULL,
  PaymentMethod ENUM('COD','VNPAY') NOT NULL,
  Status ENUM('UNPAID','PENDING','SHIPPING','DELIVERED','CANCELLED') NOT NULL DEFAULT 'UNPAID',
  TotalAmount DECIMAL(12,2) NOT NULL,
  Note TEXT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OrderItems (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderId INT NOT NULL,
  ProductVariantId INT NOT NULL,
  Quantity INT NOT NULL DEFAULT 1,
  UnitPrice DECIMAL(10,2) NOT NULL,
  TotalPrice DECIMAL(12,2) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ProductVariantId) REFERENCES ProductVariants(Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Otps (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NULL,
  Email VARCHAR(255) NULL,
  Code VARCHAR(10) NOT NULL,
  Purpose ENUM('REGISTER','RESET_PASSWORD') NOT NULL,
  ExpiresAt DATETIME NOT NULL,
  Used TINYINT(1) NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS RefreshTokens (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NOT NULL,
  Token VARCHAR(500) NOT NULL,
  ExpiresAt DATETIME NOT NULL,
  RevokedAt DATETIME NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY unique_refresh_token(Token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VnPayTransactions (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderId INT NOT NULL,
  TransactionId VARCHAR(255) NULL,
  Amount DECIMAL(12,2) NOT NULL,
  Status ENUM('PENDING','SUCCESS','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_products_brand ON Products(BrandId);
CREATE INDEX idx_products_category ON Products(CategoryId);
CREATE INDEX idx_products_active ON Products(IsActive);
CREATE INDEX idx_variants_product ON ProductVariants(ProductId);
CREATE INDEX idx_variants_color ON ProductVariants(ColorId);
CREATE INDEX idx_variants_size ON ProductVariants(SizeId);
CREATE INDEX idx_comments_product ON Comments(ProductId);
CREATE INDEX idx_comments_user ON Comments(UserId);
CREATE INDEX idx_orders_user ON Orders(UserId);
CREATE INDEX idx_cart_user ON Carts(UserId);

select * FROM Brands;